// Code generated by tygo. DO NOT EDIT.

//////////
// source: auth_sessions.go

/**
 * AuthSession is the public representation of a browser auth session.
 */
export interface AuthSession {
  ID: string; // ULID, used as cookie value
  UserID: string; // hex of ObjectID
  CSRFToken: string;
  CreatedAt: string;
  LastSeen: string;
  ExpiresAt: string;
}
/**
 * AuthSessionsRepo provides CRUD operations for auth_sessions documents.
 */
export interface AuthSessionsRepo {
}

//////////
// source: messages.go

/**
 * SessionMessage is the public representation of a session transcript entry.
 */
export interface SessionMessage {
  ID: string; // hex of internal ObjectID
  SessionID: string;
  UserID: string; // hex
  TS: string;
  Entry: string;
}
/**
 * MessagesRepo provides operations for session_messages documents.
 */
export interface MessagesRepo {
}

//////////
// source: pairing.go

/**
 * WrapperDescriptor holds the identifying info about a wrapper requesting pairing.
 */
export interface WrapperDescriptor {
  Name: string;
  OS: string;
  Arch: string;
  Version: string;
}
/**
 * PairingCode is the public representation of a pairing code document.
 */
export interface PairingCode {
  /**
   * ID + UserID exposed as hex strings (or empty for unset). Internal
   * _id and user_id are ObjectIDs in Mongo.
   */
  ID: string;
  Code: string;
  Status: string; // pending | approved | denied
  UserID: string; // empty until approved
  Wrapper: WrapperDescriptor;
  ExpiresAt: string;
}
/**
 * PairingRepo provides CRUD operations for pairing_codes documents.
 */
export interface PairingRepo {
}

//////////
// source: projects.go

/**
 * Project is the public representation of a project document. One row per
 * (wrapper, project-slug) tuple.
 */
export interface Project {
  ID: string; // hex of ObjectID
  UserID: string; // hex of ObjectID
  WrapperID: string; // hex of ObjectID
  Slug: string; // dir name under ~/.claude/projects/
  Cwd: string; // absolute cwd recovered from JSONL events
  Name: string; // basename of Cwd
  SessionCount: number /* int */;
  FirstActivityAt: string;
  LastActivityAt: string;
}
/**
 * ProjectUpsert is the wrapper-side intent for a project row.
 */
export interface ProjectUpsert {
  Slug: string;
  Cwd: string;
  Name: string;
  SessionCount: number /* int */;
  FirstActivityAt: string;
  LastActivityAt: string;
}
export interface ProjectsRepo {
}

//////////
// source: sessions.go

/**
 * Session is the public representation of a session document.
 */
export interface Session {
  ID: string;
  UserID: string; // hex string of ObjectID
  WrapperID: string; // hex string of ObjectID
  JSONLUUID: string;
  Cwd: string;
  Account: string;
  Status: string; // starting | running | exited | wrapper_offline
  CreatedAt: string;
  ExitedAt?: string;
  ExitCode?: number /* int */;
  ExitReason: string;
}
/**
 * SessionCreate holds the fields needed to create a new session.
 */
export interface SessionCreate {
  ID: string;
  UserID: string;
  WrapperID: string;
  Cwd: string;
  Account: string;
}
/**
 * SessionsRepo provides CRUD operations for sessions documents.
 */
export interface SessionsRepo {
}

//////////
// source: transcripts.go

/**
 * Transcript is the public representation of a transcripts document.
 */
export interface Transcript {
  ID: string; // hex of ObjectID
  UserID: string; // hex of ObjectID
  WrapperID: string; // hex of ObjectID
  ProjectID: string; // hex of ObjectID
  JSONLUUID: string; // filename without .jsonl, unique per wrapper
  Path: string; // relative to ~/.claude/projects/
  StartedAt: string;
  EndedAt: string;
  MessageCount: number /* int */;
  Title: string;
  Bytes: number /* int64 */;
}
/**
 * TranscriptUpsert is the wrapper-side intent for a transcript row.
 * ProjectSlug is resolved server-side to ProjectID via Projects().UpsertMany.
 */
export interface TranscriptUpsert {
  JSONLUUID: string;
  ProjectSlug: string;
  Path: string;
  StartedAt: string;
  EndedAt: string;
  MessageCount: number /* int */;
  Title: string;
  Bytes: number /* int64 */;
}
export interface TranscriptsRepo {
}

//////////
// source: users.go

/**
 * User is the persisted shape of an end-user account.
 */
export interface User {
  OID: string;
  ID: string;
  OAuthProvider: string;
  OAuthSubject: string;
  Email: string;
  Name: string;
  AvatarURL: string;
  KeepTranscripts: boolean;
  TranscriptRetentionDays: number /* int */;
  CreatedAt: string;
  LastLoginAt: string;
}
/**
 * OAuthProfile is what an OAuth provider gives us after callback.
 */
export interface OAuthProfile {
  Provider: string;
  Subject: string;
  Email: string;
  Name: string;
  AvatarURL: string;
}
/**
 * UsersRepo provides CRUD operations for users.
 */
export interface UsersRepo {
}

//////////
// source: wrappers.go

/**
 * Wrapper is the public representation of a paired wrapper instance.
 */
export interface Wrapper {
  ID: string;
  UserID: string;
  Name: string;
  OS: string;
  Arch: string;
  Version: string;
  PairedAt: string;
  LastSeenAt: string;
  RefreshTokenHash: string;
  RefreshTokenID: string;
  RevokedAt?: string;
}
/**
 * WrapperCreate holds the fields needed to register a new wrapper.
 */
export interface WrapperCreate {
  UserID: string;
  Name: string;
  OS: string;
  Arch: string;
  Version: string;
}
/**
 * WrappersRepo provides operations for wrapper documents.
 */
export interface WrappersRepo {
}
