package store

import (
	"context"
	"errors"
	"time"

	"go.mongodb.org/mongo-driver/v2/bson"
	"go.mongodb.org/mongo-driver/v2/mongo"
	"go.mongodb.org/mongo-driver/v2/mongo/options"
)

// sessionMessageDoc is the internal BSON-mapped struct for a session_messages document.
// _id is an ObjectID (auto-generated by Mongo).
type sessionMessageDoc struct {
	OID       bson.ObjectID `bson:"_id,omitempty"`
	SessionID string        `bson:"session_id"`
	UserOID   bson.ObjectID `bson:"user_id"`
	TS        time.Time     `bson:"ts"`
	Entry     string        `bson:"entry"`
}

func (d *sessionMessageDoc) toSessionMessage() *SessionMessage {
	return &SessionMessage{
		ID:        d.OID.Hex(),
		SessionID: d.SessionID,
		UserID:    d.UserOID.Hex(),
		TS:        d.TS,
		Entry:     d.Entry,
	}
}

// SessionMessage is the public representation of a session transcript entry.
type SessionMessage struct {
	ID        string // hex of internal ObjectID
	SessionID string
	UserID    string // hex
	TS        time.Time
	Entry     string
}

// MessagesRepo provides operations for session_messages documents.
type MessagesRepo struct{ coll *mongo.Collection }

// Messages returns a MessagesRepo for the store.
func (s *Store) Messages() *MessagesRepo {
	return &MessagesRepo{coll: s.db.Collection("session_messages")}
}

// Append inserts a new message entry for the given session.
func (r *MessagesRepo) Append(ctx context.Context, sessionID, userID string, ts time.Time, entry string) error {
	_, err := r.coll.InsertOne(ctx, bson.M{
		"session_id": sessionID,
		"user_id":    objectIDFromHex(userID),
		"ts":         ts.UTC(),
		"entry":      entry,
	})
	return err
}

// List returns messages for a session in ascending ts order.
// If since is non-zero, only messages with ts > since are returned.
// At most limit messages are returned.
func (r *MessagesRepo) List(ctx context.Context, sessionID string, since time.Time, limit int) ([]SessionMessage, error) {
	filter := bson.M{"session_id": sessionID}
	if !since.IsZero() {
		filter["ts"] = bson.M{"$gt": since.UTC()}
	}

	opts := options.Find().
		SetSort(bson.D{{Key: "ts", Value: 1}}).
		SetLimit(int64(limit))

	cur, err := r.coll.Find(ctx, filter, opts)
	if errors.Is(err, mongo.ErrNoDocuments) {
		return nil, nil
	}
	if err != nil {
		return nil, err
	}
	defer cur.Close(ctx)

	var out []SessionMessage
	for cur.Next(ctx) {
		var d sessionMessageDoc
		if err := cur.Decode(&d); err != nil {
			return nil, err
		}
		out = append(out, *d.toSessionMessage())
	}
	return out, cur.Err()
}
